spring.application.name=tc-book-be

app.root.username=super_admin
app.root.password=admin123
app.root.email=root@system.local

# ===== Gmail SMTP =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sonnh.buh@gmail.com
spring.mail.password=tqqlvvbyislwnnws

# ===== Security =====
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ===== Timeout =====
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===== Debug (test xong t?t) =====
spring.mail.properties.mail.debug=true

# Server
server.port=8080

# Th? m?c l?u ?nh (t? t?o n?u ch?a có)
app.upload.dir=images

# Gi?i h?n upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

