@startuml TC_Book_Class_Diagram

skinparam backgroundColor white
skinparam classAttributeIconSize 0

class User {
    username
    password
    firstName
    lastName
    phone
    email
    address
}

class Product {
    name
    slug
    description
    price
    salePrice
    quantity
    sold
    mainImageUrl
}

class Category {
    name
    slug
    imageUrl
    categoryLevel
}

class Tag {
    name
}

class Cart {
    userId
}

class CartItem {
    cartId
    productId
    quantity
}

class Order {
    userId
    totalPrice
    status
}

class OrderDetail {
    orderId
    productId
    price
    quantity
    productName
}

class Review {
    orderId
    productId
    authorName
    rating
    description
}

@enduml
